export const W               = 800;
export const H               = 600;
export const PX              = W / 2;
export const PY              = H / 2;
export const WIND_RANGE      = 230;
export const WIND_HALF_ANGLE = 0.30;   // ~17° each side
export const MAX_CATS        = 10;
export const MAX_DOGS        = 5;
export const DOG_POINTS      = 2;
export const YINZI_POINTS    = 3;
export const YINZI_SCORE_REQ = 7;   // Yinzis appear after score > 7
export const PLAYER_RADIUS   = 28;
